apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-cm-volume
  name: nginx-cm-volume
spec:
  containers:
  - image: nginx:latest
    name: nginx-cm-volume
    resources: {}
    volumeMounts:
    - name: cmvolume
      mountPath: /etc/lala
  volumes:
  - name: cmvolume
    configMap:
      name: cmvolume
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
