apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-secure
  name: nginx-secure
spec:
  securityContext:
    runAsUser: 101
  containers:
  - image: nginx
    name: nginx-secure
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
