apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pvc-busybox
  name: pvc-busybox-2
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - sleep 3600
    image: busybox
    name: pvc-busybox-2
    volumeMounts:
    - name: mypvc
      mountPath: /etc/foo
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
  - name: mypvc
    persistentVolumeClaim:
      claimName: mypvc

