apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: volume-shared-busybox
  name: volume-shared-busybox
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - sleep 3600
    image: busybox
    name: volume-shared-busybox-1
    volumeMounts:
    - mountPath: /etc/foo
      name: shared-volume
  - args:
    - /bin/sh
    - -c
    - sleep 3600
    image: busybox
    name: volume-shared-busybox-2
    volumeMounts:
    - mountPath: /etc/foo
      name: shared-volume
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
  - name: shared-volume
    emptyDir: {}
