apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sample-env-pod
  name: sample-env-pod
spec:
  containers:
  - image: nginx:1.19
    name: sample-env-pod
    resources: {}
    env:
    - name: K8S_NODE
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: CPU_REQUEST
      valueFrom:
        resourceFieldRef:
          containerName: sample-env-pod
          resource: requests.cpu
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
