apiVersion: v1
kind: Pod
metadata:
  labels:
    run: sample-secret-env-pod
  name: sample-secret-env-pod
spec:
  containers:
  - image: nginx:1.19-alpine
    name: sample-secret-env-pod
    env:
    - name: DB_USER_NAME
      valueFrom:
        secretKeyRef:
          name: sample-db-auth
          key: username
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: sample-db-auth
          key: password
    volumeMounts:
    - name: secret-volume
      mountPath: /config
      readOnly: true
  volumes:
  - name: secret-volume
    secret:
      secretName: sample-db-auth
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
